FROM python:3.13-slim

RUN apt-get -y update; apt-get -y install curl

RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:${PATH}"

ENV SAMBANOVA_BASE_URL=https://tejas.tacc.utexas.edu/v1/<modelid>
ENV SAMBANOVA_API_KEY=xyz
ENV OPENAI_API_KEY=apikey
ENV TAPIS_MCP_SERVER_BASE_URL=http://127.0.0.1:8000/mcp


# Set the working directory inside the container
WORKDIR /app
COPY pyproject.toml ./
RUN uv sync 
ENV PATH="/app/.venv/bin:$PATH"


# Copy the rest of your project's source code into the container
COPY tapis_mcp_client_header.py tapis_mcp_client_header.py
COPY app_config.py app_config.py


# Expose the port your server listens on (adjust if needed, default might be 8000)
EXPOSE 8001

# Command to run the server when the container starts (replace 'your_server_script.py' and 'main_function' with your details)
#CMD ["uv", "run", "tapis_mcp_server.py", "--factory", "tapis_mcp_server.py:main"]
ENTRYPOINT ["python"]
CMD ["tapis_mcp_client_header.py"]