FROM python:3.13-slim

RUN apt-get -y update; apt-get -y install curl

# Install system dependencies if required by your application (example: curl for specific tools)
#RUN apt-get update && apt-get install -y curl ca-certificates --no-install-recommends && rm -rf /var/lib/apt/lists/*
#RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates


RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:${PATH}"


# Set the working directory inside the container
WORKDIR /app
COPY pyproject.toml ./
RUN uv sync 
ENV PATH="/app/.venv/bin:$PATH"

# # Copy the requirements file and install dependencies first (for better Docker caching)
# COPY requirements.txt .
# RUN uv pip install --system -r requirements.txt

# Copy the rest of your project's source code into the container
COPY tapis_mcp_client_header.py tapis_mcp_client_header.py

#RUN source .venv/bin/activate

# Expose the port your server listens on (adjust if needed, default might be 8000)
EXPOSE 8001

# Command to run the server when the container starts (replace 'your_server_script.py' and 'main_function' with your details)
#CMD ["uv", "run", "tapis_mcp_server.py", "--factory", "tapis_mcp_server.py:main"]
ENTRYPOINT ["python"]
CMD ["tapis_mcp_client_header.py"]